sudo: required
services:
  - docker

before_install:
  - docker build -t myidalias/visits .

script:
  - docker run myidalias/visits npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "visits-env"
  bucket_name: "elasticbeanstalk-us-east-1-382498021366"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY_ON_TRAVISCI"
  secret_access_key:
    secure: "$AWS_SECRET_KEY_ON_TRAVISCI"
  